server:
  port: 8762
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'